spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to bankcorp accounts related Production APIs"
  contactDetails:
    name: "Petar Petrov"
    email: "petar@example.com"
  onCallSupport:
    -(222)222-2222
    -(111)111-1111