services:
  network-deploy-service:
    networks:
      - bankcorp

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      - configserver
    entrypoint: [ 'check-config-server-started.sh' ]
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    volumes:
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
