services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "tzetzaka2/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: curl -m 5 --silent --fail --request GET http://localhost:8071/actuator/health | jq --exit-status -n 'inputs | if has("status") then .status=="UP" else false end' > /dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

#  accounts:
#    image: "tzetzaka2/accounts:s6"
#    container_name: accounts-ms
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_APPLICATION_NAME: "accounts"
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config
#
#  loans:
#    image: "tzetzaka2/loans:s6"
#    container_name: loans-ms
#    ports:
#      - "8090:8090"
#    environment:
#      SPRING_APPLICATION_NAME: "loans"
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config
#
#  cards:
#    image: "tzetzaka2/cards:s6"
#    container_name: cards-ms
#    ports:
#      - "9000:9000"
#    environment:
#      SPRING_APPLICATION_NAME: "cards"
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config

networks:
  bankcorp:
    driver: "bridge"